=== cocobongos/taller2/xml/modelo-rep.dtd
<!ELEMENT Proyecto (Diagrama+)>
<!ELEMENT Diagrama (Representacion+)>
<!ELEMENT Representacion (Posicion, Dimension, ColorFondo?, ColorLinea?, Representacion*)>
<!ELEMENT Posicion (#PCDATA)>
<!ELEMENT Dimension (#PCDATA)>
<!ELEMENT ColorFondo (#PCDATA)>
<!ELEMENT ColorLinea (#PCDATA)>

<!ATTLIST Diagrama id ID #REQUIRED>
<!ATTLIST Representacion id ID #REQUIRED>

<!ATTLIST Posicion x CDATA #REQUIRED>
<!ATTLIST Posicion y CDATA #REQUIRED>

<!ATTLIST Dimension ancho CDATA #REQUIRED>
<!ATTLIST Dimension alto CDATA #REQUIRED>

<!ATTLIST ColorFondo r CDATA #REQUIRED>
<!ATTLIST ColorFondo g CDATA #REQUIRED>
<!ATTLIST ColorFondo b CDATA #REQUIRED>

<!ATTLIST ColorLinea r CDATA #REQUIRED>
<!ATTLIST ColorLinea g CDATA #REQUIRED>
<!ATTLIST ColorLinea b CDATA #REQUIRED>

=== cocobongos/taller2/xml/ejemplos/test-rep.xml
<!DOCTYPE note SYSTEM "../modelo-rep.dtd">
<Proyecto>
	<Diagrama id="_41">
		<Representacion id="_1">
			<Posicion x="100" y="100" />
			<Dimension ancho="100" alto="30" />
			<ColorFondo r="255" g="255" b="210" />
			<ColorLinea  r="0" g="0" b="0" />
		</Representacion>
		<Representacion id="_24">
			<Posicion x="150" y="150" />
			<Dimension ancho="100" alto="50" />
		</Representacion>
		<Representacion id="_27">
			<Posicion x="150" y="200" />
			<Dimension ancho="100" alto="50" />
		</Representacion>
		<Representacion id="_30">
			<Posicion x="150" y="250" />
			<Dimension ancho="100" alto="50" />
		</Representacion>
	</Diagrama>
</Proyecto>
